name: app
description: Athmany Tec APP-APP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 4.11.2+2
version: 4.30.10+158

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
#  data_connection_checker_tv: ^0.3.5-nullsafety
  connectivity_plus: ^2.3.7
  dio: ^4.0.0
#  flutter_session:
#    git:
#      url: https://github.com/alnobanidevelop/flutter_session
#      ref: master
  sqflite:
  provider: ^4.3.3
  get: ^4.6.0
  #  path_provider: ^2.0.7
  # intl: ^0.16.1
  flutter_html: ^0.11.1
  html: ^0.15.0
  charset_converter:
  fluttertoast: ^8.0.3
  loading_overlay:
  url_launcher: ^6.0.16
  flutter_svg: ^0.19.1
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.9
  shared_preferences_platform_interface: ^2.0.0-nullsafety
  cached_network_image: ^3.2.1
  scroll_to_index: ^3.0.1
#  sunmi_printer_plus:
#    git: https://github.com/JoDeveloper/sunmi_printer_plus.git
#  flutter_sunmi_printer_t2: ^0.0.3
#  sunmi_printer_plus: ^2.1.0
  flutter_phoenix: ^1.0.0
  network_image_to_byte: ^0.0.1
  pausable_timer: ^1.0.0+5
  esc_pos_printer: ^4.0.3
  esc_pos_utils: ^1.1.0
  xml: ^5.0.0
  device_info: ^2.0.1
  flutter_typeahead: ^4.0.0
  passcode_screen: ^1.2.2+1
  change_app_package_name: ^1.0.0
  virtual_keyboard_multi_language: ^0.2.4
  auto_size_text: ^3.0.0
  qr_flutter: ^4.0.0
  collection: ^1.15.0
  location: ^2.5.4
  sentry_flutter: ^6.5.1
  ping_discover_network: ^0.2.0+1
  wifi: ^0.1.5
dependency_overrides:
  shared_preferences: ^2.0.15
  shared_preferences_platform_interface: ^1.0.0
  platform: ^3.1.0
  html: ^0.14.0
  xml: ^4.2.0
  flutter_easyloading: ^3.0.5
  loading_animation_widget: ^1.2.0+2
  flutter_animated_dialog: ^2.0.1
  nil: ^1.1.1
  flutter_hooks: ^0.18.5+1
  new_version: ^0.3.1
  launch_review:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    # side menu (green bar)
    - assets/side-menu/
    - assets/icons/
    - assets/footer/
    - lib/lang/ar.json
    - lib/lang/en.json


  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/cairo/Cairo-Regular.ttf
    - family: CairoSemiBold
      fonts:
        - asset: fonts/cairo/Cairo-SemiBold.ttf
    - family: CairoBold
      fonts:
        - asset: fonts/cairo/Cairo-Bold.ttf
    - family: CairoBlack
      fonts:
        - asset: fonts/cairo/Cairo-Black.ttf
    - family: CairoLignt
      fonts:
        - asset: fonts/cairo/Cairo-Light.ttf
    - family: CairoExtraLignt
      fonts:
        - asset: fonts/cairo/Cairo-ExtraLight.ttf
